use crate::{
    instruction_information::{ArgumentType, InstructionInformation, InstructionType},
    operation::{ImmediateOp, Operation, Special1Op},
};

const NUM_OF_REGISTERS: usize = 32;

pub const REGISTERS: [&'static str; NUM_OF_REGISTERS] = [
    "$zero", "$at", "$v0", "$v1", "$a0", "$a1", "$a2", "$a3", "$t0", "$t1", "$t2", "$t3", "$t4",
    "$t5", "$t6", "$t7", "$s0", "$s1", "$s2", "$s3", "$s4", "$s5", "$s6", "$s7", "$t8", "$t9",
    "$k0", "$k1", "$gp", "$sp", "$fp", "$ra",
];

pub const INSTRUCTION_SET: &[InstructionInformation] = &[
    InstructionInformation {
        mnemonic: "add",
        operation: Operation::Special1(Special1Op::Add),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "addi",
        operation: Operation::Immediate(ImmediateOp::Addi),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Rs, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "addiu",
        operation: Operation::Immediate(ImmediateOp::Addiu),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Rs, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "addu",
        operation: Operation::Special1(Special1Op::Addu),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "and",
        operation: Operation::Special1(Special1Op::And),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "andi",
        operation: Operation::Immediate(ImmediateOp::Andi),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Rs, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "beq",
        operation: Operation::Immediate(ImmediateOp::Beq),
        instruction_type: InstructionType::IType,
        args: &[
            ArgumentType::Rs,
            ArgumentType::Rt,
            ArgumentType::BranchLabel,
        ],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "bgtz",
        operation: Operation::Immediate(ImmediateOp::Bgtz),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rs, ArgumentType::BranchLabel],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "blez",
        operation: Operation::Immediate(ImmediateOp::Blez),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rs, ArgumentType::BranchLabel],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "bne",
        operation: Operation::Immediate(ImmediateOp::Bne),
        instruction_type: InstructionType::IType,
        args: &[
            ArgumentType::Rs,
            ArgumentType::Rt,
            ArgumentType::BranchLabel,
        ],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "j",
        operation: Operation::Immediate(ImmediateOp::J),
        instruction_type: InstructionType::JType,
        args: &[ArgumentType::BranchLabel],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "jal",
        operation: Operation::Immediate(ImmediateOp::Jal),
        instruction_type: InstructionType::JType,
        args: &[ArgumentType::BranchLabel],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "jalr",
        operation: Operation::Special1(Special1Op::Jalr),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs],
        alt_args: Some(&[&[ArgumentType::Rs]]),
    },
    InstructionInformation {
        mnemonic: "jr",
        operation: Operation::Special1(Special1Op::Jr),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rs],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "lb",
        operation: Operation::Immediate(ImmediateOp::Lb),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Immediate, ArgumentType::Rs],
        alt_args: Some(&[
            &[ArgumentType::Rt, ArgumentType::Rs],
            &[ArgumentType::Rt, ArgumentType::Identifier, ArgumentType::Rs],
        ]),
    },
    InstructionInformation {
        mnemonic: "lui",
        operation: Operation::Immediate(ImmediateOp::Lui),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "lw",
        operation: Operation::Immediate(ImmediateOp::Lw),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Immediate, ArgumentType::Rs],
        alt_args: Some(&[
            &[ArgumentType::Rt, ArgumentType::Rs],
            &[ArgumentType::Rt, ArgumentType::Identifier, ArgumentType::Rs],
        ]),
    },
    /*
      Instruction::InstructionInformation {
        mnemonic: "mfhi",
        operation: Operation::Special1(Special1Op::Mfhi),
        instruction_type: InstructionType::RType,
        opcode: None,
        funct: Some(16),
        args: &[ArgumentType::Rd],
        alt_args: None,
    },
      Instruction::InstructionInformation {
        mnemonic: "mflo",
        operation: Operation::Special1(Special1Op::Mflo),
        instruction_type: InstructionType::RType,
        opcode: None,
        funct: Some(18),
        args: &[ArgumentType::Rd],
        alt_args: None,
    },
    */
    InstructionInformation {
        mnemonic: "nor",
        operation: Operation::Special1(Special1Op::Nor),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "nop",
        operation: Operation::Special1(Special1Op::Sll),
        instruction_type: InstructionType::RType,
        args: &[],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "or",
        operation: Operation::Special1(Special1Op::Or),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "ori",
        operation: Operation::Immediate(ImmediateOp::Ori),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Rs, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "sb",
        operation: Operation::Immediate(ImmediateOp::Sb),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Immediate, ArgumentType::Rs],
        alt_args: Some(&[
            &[ArgumentType::Rt, ArgumentType::Rs],
            &[ArgumentType::Rt, ArgumentType::Identifier, ArgumentType::Rs],
            &[ArgumentType::Rt, ArgumentType::Identifier],
        ]),
    },
    InstructionInformation {
        mnemonic: "sll",
        operation: Operation::Special1(Special1Op::Sll),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rt, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "slt",
        operation: Operation::Special1(Special1Op::Slt),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "slti",
        operation: Operation::Immediate(ImmediateOp::Slti),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Rs, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "sltiu",
        operation: Operation::Immediate(ImmediateOp::Sltiu),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Rs, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "sltu",
        operation: Operation::Special1(Special1Op::Sltu),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "srl",
        operation: Operation::Special1(Special1Op::Srl),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rt, ArgumentType::Immediate],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "sub",
        operation: Operation::Special1(Special1Op::Sub),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "subu",
        operation: Operation::Special1(Special1Op::Subu),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "sw",
        operation: Operation::Immediate(ImmediateOp::Sw),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Immediate, ArgumentType::Rs],
        alt_args: Some(&[
            &[ArgumentType::Rt, ArgumentType::Rs],
            &[ArgumentType::Rt, ArgumentType::Identifier, ArgumentType::Rs],
            &[ArgumentType::Rt, ArgumentType::Identifier],
        ]),
    },
    InstructionInformation {
        mnemonic: "syscall",
        operation: Operation::Special1(Special1Op::Syscall),
        instruction_type: InstructionType::RType,
        args: &[],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "xor",
        operation: Operation::Special1(Special1Op::Xor),
        instruction_type: InstructionType::RType,
        args: &[ArgumentType::Rd, ArgumentType::Rs, ArgumentType::Rt],
        alt_args: None,
    },
    InstructionInformation {
        mnemonic: "xori",
        operation: Operation::Immediate(ImmediateOp::Xori),
        instruction_type: InstructionType::IType,
        args: &[ArgumentType::Rt, ArgumentType::Rs, ArgumentType::Immediate],
        alt_args: None,
    },
];
